services:
  - type: web
    name: fazle-ai-health-api
    runtime: docker
    plan: free

    healthCheckPath: /health

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_VERSION
        value: 1.0.0
      - key: LLM_BASE_URL
        value: https://generativelanguage.googleapis.com/v1beta
      - key: LLM_MODEL
        value: gemini-2.5-flash
      - key: LLM_TIMEOUT_SECONDS
        value: '10'
      - key: GEMINI_API_KEY
        sync: false
